//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;


    public partial class Users
    {
        public int UserID { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        public string UserName { get; set; }
        [Required(ErrorMessage ="This field is required.")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        public Nullable<int> Libary_Card { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        [DisplayName("Confirm Password")]
        [DataType(DataType.Password)]
        [Compare("Password")]
        public string ConfirmPassword { get; set; }

        public virtual Patrons Patrons { get; set; }
    }
}
